app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'

urlpatterns=[
    path('hai/',hai,name='hai'),
    path('hello/',hello,name='hello'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'

urlpatterns=[
    path('hai/',hai,name='hai'),
    path('hello/',hello,name='hello'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def hai(request):
    return render(request,'hai.html')

def hello(request):
    return render(request,'hello.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def hai(request):
    return render(request,'hai.html')

def hello(request):
    return render(request,'hello.html')
    

templates/hai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=s, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hai</h1>
        <h6><a href="{% url 'app2:hello'%}">click to go to hello page</a></h6>
    </center>
</body>
</html>

templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hello</h1>
        <h6><a href="{% url 'app1:hai' %}">click to go to hai page</a></h6>
    </center>
</body>
</html>